# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10gfvYV-xriokNmdYRfTb8v1coAonnCZj
"""

# ETE PORTO DIGITAL
#DISCIPLINA:PLC1
#PROFESSOR:CLOVES
#ESTUDANTE:?
print ('OLA,PORTO DIGITAL!')